evaluation-service:
  property: Evaluation Profile Dev

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/tg_evaluation_service_db
  datasource:
    url: jdbc:postgresql://localhost:5432/tg_assignments_db
    username: ${DB_USER_POSTGRES}
    password: ${DB_PASSWORD_POSTGRES}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/

server:
  port: 8083