server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # USER-SERVICE
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<remaining>.*)/user-service/${remaining}
        # PROGRAM-ADMIN-SERVICE
        - id: program-admin-service
          uri: lb://program-admin-service
          predicates:
            - Path=/api/v1/applications/**
        # NOTIFICATION SERVICE
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
        # EVALUATION-SERVICE
        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
            - Path=/evaluation/api/v1/**
          filters:
            - RewritePath=/evaluation/api/v1/(?<remaining>.*), /evaluation-service/api/v1/${remaining}
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods:
              - OPTIONS
              - HEAD
              - GET
              - PUT
              - POST
              - DELETE
              - PATCH            