notification-service:
  property: Notification Profile Dev

spring:
  mail:
    port: 587
    host: smtp.gmail.com
    username: iriarte.bootcamp@gmail.com
    password: klyejpqboynsendr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8087
